# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '9.0'

target 'FirebaseLogin' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FirebaseLogin
  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/Auth', '~> 5.15.0'
  pod 'Firebase/Firestore', '~> 5.15.0'
  pod 'Firebase/Analytics', '~> 5.15.0'
  # pod 'Firebase/Database', '~> 5.3.0'
  pod 'Firebase/Messaging', '~> 5.15.0'
  pod 'ReactNativeNavigation', :path => '../node_modules/react-native-navigation'
  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'React', :path => '../node_modules/react-native'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

end
